In [1]:
import numpy as np

In [2]:
a = np.array([3,6,5,4,9])
print(a)

[3 6 5 4 9]


In [3]:
a

array([3, 6, 5, 4, 9])

In [6]:
b = np.array([5,2,3,7,8,9,4])
s = np.sort(b)
print(s)

[2 3 4 5 7 8 9]


In [7]:
r = np.flip(s)

In [8]:
r

array([9, 8, 7, 5, 4, 3, 2])

In [9]:
s

array([2, 3, 4, 5, 7, 8, 9])

In [13]:
Adds = np.add(r,s)
sub = np.subtract(r,s)
mul = np.multiply(r,s)
div = np.divide(r,s)

In [15]:
Adds

array([11, 11, 11, 10, 11, 11, 11])

In [16]:
sub

array([ 7,  5,  3,  0, -3, -5, -7])

In [17]:
mul

array([18, 24, 28, 25, 28, 24, 18])

In [18]:
div

array([4.5       , 2.66666667, 1.75      , 1.        , 0.57142857,
       0.375     , 0.22222222])

In [19]:
print(type(a))

<class 'numpy.ndarray'>


In [20]:
print(a.ndim)

1


In [21]:
b.ndim

1

In [23]:
r.ndim

1

In [24]:
s.ndim

1

In [27]:
ber = np.array([2,6,7,4,3,3])
res = ber.reshape(2,3)
print(res)

[[2 6 7]
 [4 3 3]]


In [35]:
shape = np.array([56,34,67,89,12,45,66,88,90,34,28,39])
three_dim = shape.reshape(3,2,2)
print(three_dim)

[[[56 34]
  [67 89]]

 [[12 45]
  [66 88]]

 [[90 34]
  [28 39]]]
